---
# Use with pre-commit.
# See usage instructions at https://pre-commit.com website.
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v3.2.0"
    hooks:
      - id: end-of-file-fixer
        name: "pre-commit/pre-commit-hooks/end-of-file-fixer"
        description: |-
          This hook fixes end of file.
          https://github.com/pre-commit/pre-commit-hooks/tree/master/pre_commit_hooks
        entry: end-of-file-fixer
        language: python
        types: [text]
      - id: trailing-whitespace
        name: "pre-commit/pre-commit-hooks/trailing-whitespace"
        description: |-
          This hook trims trailing whitespace.
          https://github.com/pre-commit/pre-commit-hooks/tree/master/pre_commit_hooks
        entry: trailing-whitespace-fixer
        language: python
        types: [text]
      - id: check-yaml
        name: "pre-commit/pre-commit-hooks/check-yaml"
        description: |-
          This hook loads all yaml files to verify syntax.
          https://github.com/pre-commit/pre-commit-hooks/tree/master/pre_commit_hooks
        entry: check-yaml
        args: ["--allow-multiple-documents"]
        language: python
        types: ["file", "non-executable", "text", "yaml"]
  - repo: https://github.com/prettier/prettier
    rev: "2.1.2"
    hooks:
      - id: prettier
        name: "prettier/prettier"
        description: |-
          Prettier is an opinionated code formatter.
          https://prettier.io/
          https://github.com/prettier/prettier/blob/master/.pre-commit-hooks.yaml
        entry: prettier --write --list-different --ignore-unknown
        types: ["file", "non-executable", "text"]
  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.25.0"
    hooks:
      - id: yamllint
        name: "adrienverge/yamllint"
        description: |-
          Yamllint is a static analysis tool for YAML files.
          https://yamllint.readthedocs.io/en/stable/
        entry: yamllint
        args: [--config-file=.yamllint.yaml]
        language: python
        types: ["file", "non-executable", "text", "yaml"]
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: "v0.1.10"
    hooks:
      - id: shellcheck
        name: "gruntwork-io/pre-commit/shellcheck"
        types: ["executable", "file", "shell", "text"]
      - id: gofmt
        name: "gruntwork-io/pre-commit/gofmt"
        types: ["file", "go", "non-executable", "text"]
      - id: golint
        name: "gruntwork-io/pre-commit/golint"
        types: ["file", "go", "non-executable", "text"]
      - id: terraform-fmt
        name: "gruntwork-io/pre-commit/terraform-fmt"
        types: ["file", "non-executable", "terraform", "text"]
      # - id: terraform-validate
      #   name: "gruntwork-io/pre-commit/terraform-validate"
      #   types: ["file", "non-executable", "terraform", "text"]
      - id: tflint
        name: "gruntwork-io/pre-commit/tflint"
        types: ["file", "non-executable", "terraform", "text"]
