---
# https://github.com/marketplace/actions/pre-commit
name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - name: "Install Terraform"
        run: |
          brew install terraform@0.12 tflint
      - name: "Initialize Terraform"
        run: |
          terraform init
      - uses: pre-commit/action@v2.0.0
