---
# https://github.com/hashicorp/terraform-foundational-policies-library/blob/master/.github/workflows/sentinel.yml
name: sentinel

on:
  pull_request:
  push:

jobs:
  sentinel-format-and-test:
    runs-on: ubuntu-latest
    container:
      # image: thrashr888/sentinel-simulator
      image: docker.io/library/debian:10-slim
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Advanced Package Tool"
        run: |-
          apt-get update \
          && apt-get install \
            --assume-yes \
            --no-install-recommends \
            ca-certificates=* \
            curl=* \
            unzip=* \
          && apt-get clean \
          && rm \
            --force \
            --recursive \
            /var/lib/apt/lists/*
      - name: "Install Sentinel"
        env:
          SENTINEL_VERSION: 0.16.1
        run: |-
          curl \
            --show-error \
            --silent \
            --request GET \
            https://releases.hashicorp.com/sentinel/${SENTINEL_VERSION}/sentinel_${SENTINEL_VERSION}_linux_amd64.zip \
            --output \
            sentinel_${SENTINEL_VERSION}_linux_amd64.zip \
          && unzip -d /usr/local/bin \
            sentinel_${SENTINEL_VERSION}_linux_amd64.zip
      - name: "Sentinel Format"
        run: sentinel fmt -check=true $(find . -name "*.sentinel" -type f)
      - name: "Sentinel Test"
        run: sentinel test $(find . -name "*.sentinel" ! -path "*/testdata/*" ! -path "*/examples/*")
  # sentinel-test:
  #   needs: sentinel-format
  #   runs-on: ubuntu-latest
  #   container:
  #     image: thrashr888/sentinel-simulator
  #   steps:
  #     - name: "Checkout"
  #       uses: actions/checkout@v2
  #     - name: "Sentinel Test"
  #       run: sentinel test $(find . -name "*.sentinel" ! -path "*/testdata/*" ! -path "*/examples/*")
